{% set version = "3.1.2" %}

package:
  name: secretstorage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/S/SecretStorage/SecretStorage-{{ version }}.tar.gz
  sha256: 15da8a989b65498e29be338b3b279965f1b8f09b9668bd8010da183024c8bff6

build:
  number: 1
  skip: True  # [win or osx or py<35]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jeepney
    - cryptography
    - dbus

test:
  imports:
    - secretstorage

about:
  home: https://github.com/mitya57/secretstorage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Provides a way for securely storing passwords and other secrets.'
  description: |
    This module provides a way for securely storing passwords and other secrets.
    It uses D-Bus Secret Service API that is supported by GNOME Keyring (since 
    version 2.30) and KSecretsService.
    The main classes provided are secretstorage.Item, representing a secret item 
    (that has a label, a secret and some attributes) and secretstorage.Collection, 
    a place items are stored in.
    SecretStorage supports most of the functions provided by Secret Service, 
    including creating and deleting items and collections, editing items, locking 
    and unlocking collections (asynchronous unlocking is also supported).
  doc_url: https://secretstorage.readthedocs.io/en/latest/
  dev_url: https://github.com/mitya57/secretstorage

extra:
  recipe-maintainers:
    - CurtLH
    - ccordoba12 
